### ISSUE TITLE
(possibly) corrupted .npy file in slp_real_cleaned data

### ISSUE THREAD

**Issue by timbektu** [Healthcare-Robotics/BodyPressure#11]
It seems that the file `slp_real_cleaned/depth_onlyhuman_0to102.npy'` is corrupted. I tried `allow_pickle=True` as well but I am able to read this file. What am I missing here?

```~/Doc/c/BodyPressure/viz_data_only on master !3 ?8 ❯ python viz_SLP3Dfits.py --p_idx 77 --pose_num 13 --ctype 'uncover' --viz '3D' 
`COULD NOT IMPORT 03D 
COULD NOT IMPORT 03D
importing load model3
viz_SLP3Dfits.py:76: DeprecationWarning: Please use `gaussian_filter` from the `scipy.ndimage` namespace, the `scipy.ndimage.filters` namespace is deprecated.
  from scipy.ndimage.filters import gaussian_filter
viz_SLP3Dfits.py:78: DeprecationWarning: Please use `zoom` from the `scipy.ndimage` namespace, the `scipy.ndimage.interpolation` namespace is deprecated.
  from scipy.ndimage.interpolation import zoom
17 103.87 182.0 mass ht
74 105.1 178.0 mass ht
[ 85.6 180.    1.   93.  101.  107.   30.   26.   50.5  36. ]
Traceback (most recent call last):
  File "viz_SLP3Dfits.py", line 446, in <module>
    F_eval = V3D.evaluate_data(testing_database_file_f, testing_database_file_m)
  File "viz_SLP3Dfits.py", line 165, in evaluate_data
    test_dat_f_slp = SLPPrepLib().load_slp_files_to_database(testing_database_file_f, dana_lab_path, PM = opt.ctype, depth = opt.ctype, color = None, mass_ht_list=all_f_subj_mass_ht_list, markers_gt_type = '3D', use_pc = True, pm_adjust_mm = self.CTRL_PNL['x_y_offset_synth'])
  File "/home/argo/Documents/capstone/BodyPressure/viz_data_only/../lib_py/slp_prep_lib_bp.py", line 142, in load_slp_files_to_database
    **depth_onlyhuman_0to102 = np.load(FILEPATH+'data_BP/slp_real_cleaned/depth_onlyhuman_0to102.npy')**
  File "/home/argo/miniconda3/envs/capstone/lib/python3.8/site-packages/numpy/lib/npyio.py", line 438, in load
    raise ValueError("Cannot load file containing pickled data "
ValueError: Cannot load file containing pickled data when allow_pickle=False```

**Comment by henryclever** [comment]
Hi, try adding a flag `allow_pickle=True` to the call --
`np.load(FILEPATH+'data_BP/slp_real_cleaned/depth_onlyhuman_0to102.npy', allow_pickle=True)`

And let me know if that works.

-Henry

**Comment by timbektu** [comment]
Like I mentioned, I tried passing `allow_pickle=True ` but I run into similar issues with loading the .npy file.

**Comment by henryclever** [comment]
Hm - what error are you getting with that? I just tried downloading it and loading it in a python script and it loads + prints the data fine. I get a shape of `(102, 45, 128, 54)`.

-Henry

**Comment by henryclever** [comment]
Ah, the issues was wrong URL in the download sh file. I just fixed locally, will push soon, thanks.

**Comment by DavidTu21** [comment]
Dear Henry,

I hope you are doing well! May I ask that if this change has been pushed now? I also face this same error even with the 'allow_pickel = True'. Or will it possible that you could point me where to download the correct file? Thank you very much for your time.

Kind regards,
David

**Comment by thraster** [comment]
Hey Henry,
I came across with the same question recently, have you fixed the URL now?

**Comment by thraster** [comment]
I download them from [here](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/ZS7TQS&version=1.0&selectTab=termsTab) and put them into the correct folder now everything is working good.
