### ISSUE TITLE
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/C6J1SP .p files

### ISSUE THREAD

**Issue by liora-liora** [Healthcare-Robotics/BodyPressure#12]
Hey Henry! Great work. 
I have no idea how to open the .p files here: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/C6J1SP
The free pascal compiler said there are damages.
So how do I open them?

**Comment by Tandon-A** [comment]
Hi @liora-liora , 

These are pickle files which can be opened through python script. 

```python
import pickle as pkl
def load_pickle(filename):
    with open(filename, 'rb') as f:
        return pkl.load(f, encoding = 'latin1')

data = load_pickle(full_path_to_pickle_file)
```

**Comment by liora-liora** [comment]
> Hi @liora-liora ,
> 
> These are pickle files which can be opened through python script.
> 
> ```python
> import pickle as pkl
> def load_pickle(filename):
>     with open(filename, 'rb') as f:
>         return pkl.load(f, encoding = 'latin1')
> 
> data = load_pickle(full_path_to_pickle_file)
> ```

Thanks! But how do I visualize it? I mean there should be several information for each .p file right? 1. a depth image occluded by blankets 2. a depth image not occluded by blankets 3. a pressure image, a resting human pose in the global frame, 4. a body shape.

How do I extract all this information from one .p file? because the len of the variable data = 3, So I don't think it contains the synthetic pressure map.

Moreover, I got 37 .p files. Do they contain all the information- 97,000 samples? 

I am sorry for the confusion. This is my first time working with pickle files. Thank you so much for your help.

**Comment by henryclever** [comment]
Hi, sorry for the delay.

Yes, these 37 p files contain all 97,000 synthetic samples. They are in buckets of 6000-9000 ish -- the number on each indicates how many samples are in a particular file. 

Did you try to visualize it yet using the instructions on the readme? You can do a traceback and look through the code to see where the pickle files are read in, once you get some data visualized.

Pickle files can contain any kind of python object. I think a lot of the data is stored in a dict - where the keys in the dict point to various types of data (e.g. pressure imgs, joint angles, gender, etc).
