### ISSUE TITLE
Pressure Clipping

### ISSUE THREAD

**Issue by Tandon-A** [Healthcare-Robotics/BodyPressure#13]
Hello Henry, 

In the [estimate pose function](https://github.com/Healthcare-Robotics/BodyPressure/blob/master/networks/evaluate_depthreal_slp.py#L629) in evaluate_depthreal_slp.py file, you are first calling preprocessing_create_pressure_only_stack which [clips pressure image](https://github.com/Healthcare-Robotics/BodyPressure/blob/master/lib_py/preprocessing_lib_bp.py#L738) to be between [0, 100].But in CAL net training, I couldn't see a call to this function.

Are pressure images (synthetic from BodyPressure + real from SLP) clipped to this range in data processing?

Excluding this clipping from the evaluate function, I see that the BodyPressure model's v2vP metric (vertex to vertex Pressure metric) increases to about 3.3. (Earlier 2.8).

**Comment by henryclever** [comment]
Hi Abhishek,

Yes, it's definitely clipped from 0-100. The real pressure mat does not give values outside that range. 

All pressure images in the dataset should have values no greater than 100.

I'm not sure what metric this is for v2vP you are referring to - is this an overall error? Or?

**Comment by henryclever** [comment]
Even if the training function doesn't clip it, the ground truth should still only have values 100 max, so in this case the network needs to learn to do the clip at 100 itself.
