### ISSUE TITLE
BPB Models

### ISSUE THREAD

**Issue by Tandon-A** [Healthcare-Robotics/BodyPressure#16]
Hi Henry, 

Would it be possible for you to share pretrained BPB models, if you still have them? (And any script/code changes/commands one would need to run it)

Best, 
Abhishek

**Comment by henryclever** [comment]
I don't have any of these models, but they should be easy to get with a fresh clone of the repo - go to the "Training BodyPressure deep networks" section of the README and run the commands in it for BPB net. (just slightly different flag than BPW net). testing should work in the same way.

**Comment by Tandon-A** [comment]
Understood. Thank you
