### ISSUE TITLE
SLP-3D Fits Generation Code

### ISSUE THREAD

**Issue by Tandon-A** [Healthcare-Robotics/BodyPressure#17]
Hello Henry, 

Can you provide access to SLP-3D fits generation code? In the repository there is a file which lets me view the fits, but I wanted to understand the generation process. 

Best, 
Abhishek

**Comment by henryclever** [comment]
Unfortunately I don't have this code - Patrick Grady did it. He used the optimization method from Hassan 2020 (https://arxiv.org/pdf/2012.11581.pdf) and modified it and did a bunch of per-pose parameter tweaks to make sure all the poses were kosher. The key to it optimizing the point cloud points to the top surface of the mesh -- and getting the filters for each of them *just right* to knock out the background in the point cloud and also knock out the downfacing vertices in the mesh --- as well as to optimize over the 2D keypoints to x,y coordinates of the SMPL joints. Let me know if I can provide more information to help you or if I should get a conversation started with Patrick.

-H

**Comment by henryclever** [comment]
One of the challenges was some of the point clouds for example had various folds in the blanket, which were hard to knock out and had to be addressed on a per-pose sample basis. But we both went through all of them by hand to make sure they were good.
