### ISSUE TITLE
Incorrect depth file url

### ISSUE THREAD

**Issue by Tandon-A** [Healthcare-Robotics/BodyPressure#18]
Hello Henry, 

The url link to a depth file is incorrect in the download_BodyPressureSD.sh script. 

At [L29](https://github.com/Healthcare-Robotics/BodyPressure/blob/master/data_BP/download_BodyPressureSD.sh#L29) it should be 4**6**42077 instead of 4**5**42077. 

The correct url for train_slp_lay_f_41to70_6608_depthims.p being https://dataverse.harvard.edu/api/access/datafile/4642077

Best, 
Abhishek

**Comment by henryclever** [comment]
Thanks! just fixed this locally, will push with some other fixes.
