### ISSUE TITLE
Generating synthetic depth image from FleX

### ISSUE THREAD

**Issue by WangYixuan12** [Healthcare-Robotics/BodyPressure#2]
Hi! I just came across this work and found it very interesting. As mentioned in the README, this repo contains codes for generating synthetic depth images from FleX, but it seems that the code is not included. I am interested in its implementation. Could you please elaborate a bit on this?

**Comment by henryclever** [comment]
Hi Yixuan,

It's great you are interested in this! Yes, good question.

The code for FleX is in my other repo: https://github.com/Healthcare-Robotics/bodies-at-rest Scroll down to the bottom and it has instructions for setting things up in FleX (and also Dart ...) . Happy to answer more specific questions about this. Fair warning that it may be difficult to get it all going again given that it is in python 2.7 and the code is spread out across multiple repos. 

I believe this other repo only has the part with the synthetic pressure mat and the deformable bed. The "BodyPressure" work here has the addition of blankets and depth image rendering. But both of these are pretty easy in comparison to the previous implementation. There was no system ID on the blankets - I just dropped them on the bodies and rendered a pinhole depth camera. So if you do get the FleX (and potentially Dart, if you want articulated multi body dynamic humans) going from the 2020 CVPR repo, it shouldn't be difficult for you to add blankets and a depth camera rendering. Depth rendering is not done in FleX anyway -- FleX outputs meshes for everything and you do depth simulation elsewhere, with whatever camera model you choose.

I have all of the meshes for my dataset available, so if you want to use these and render your own camera model (whether it is RGB, or depth, or fisheye, etc) it will not require FleX.

-Henry

**Comment by WangYixuan12** [comment]
Got it. Thanks!
