### ISSUE TITLE
No mention of how to obtain contents of folder "SLP_SMPL_fits"

### ISSUE THREAD

**Issue by eitan905** [Healthcare-Robotics/BodyPressure#3]
Hi henry, I am trying to train and test the model but ran into a problem getting the contents for SLP_SMPL_fits folder.
I suspect it comes from running https://github.com/pgrady3/SLP-3Dfits but it isn't the clearest, so may be worth clarifying it thx!

**Comment by henryclever** [comment]
Hi, the contents for the `SLP_SMPL_fits` folder are all inside that repo - so just clone it and move things accordingly. 

```
SLP-3Dfits data: 4,545 SMPL bodies fit to 101 participants in the SLP dataset using mesh vertex to point cloud point optimization. This is 18 MB.

Follow the instructions in the following repo: https://github.com/pgrady3/SLP-3Dfits
Then, put it in the data_BP folder.
```

It should be here (according to README): 

```
BodyPressure
├── data_BP
│   ├── SLP_SMPL_fits
│   │   └── fits
│   │       ├── p001
│   │       .
│   │       └── p102
```

Let me know if you are able to get things copied in that way -
-Henry

**Comment by eitan905** [comment]
thx!
